; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "qqq-craft"
#define MyAppVersion GetVersionNumbersString("dist\qqq-craft\qqq-craft.exe")
#define MyAppPublisher "https://qqq-craft.top"
#define MyAppURL "https://qqq-craft.top"
#define MyAppExeName "qqq-craft.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{97C84D59-A25D-4262-84EC-51D920EFF3D0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={userappdata}\{#MyAppName}
DisableDirPage=no
DirExistsWarning=no
UsePreviousAppDir=yes
UninstallDisplayIcon={app}\qqq-craft.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=dist
OutputBaseFilename=qqq-craft
SetupIconFile=web\static\logo.ico
WizardSmallImageFile=web\static\logo-small.bmp
SolidCompression=yes
WizardStyle=modern
SignTool=Sign

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\qqq-craft\qqq-craft.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\qqq-craft\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    SaveStringToFile(ExpandConstant('{app}\game-dir.txt'),
                     ExpandConstant('{app}\game'), False);
end;

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\qqq-craft.exe"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\qqq-craft.exe"; Tasks: desktopicon

[UninstallDelete]
Type: files; Name: "{app}\game-dir.txt"

[Run]
Filename: "{app}\qqq-craft.exe"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

