name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_version
        run: |
          latest_tag=$(git ls-remote --tags --sort="version:refname" origin | tail -n1 | awk -F'/' '{print $NF}')
          if [[ -z "$latest_tag" ]]; then
            latest_tag="1.0.0.0"
          else
            latest_version=$(echo $latest_tag | sed 's/^v//')
            IFS='.' read -r major minor patch build <<< "$latest_version"
            patch=$((patch + 1))
            latest_tag="$major.$minor.$patch.0"
          fi
          echo "new_version=$latest_tag" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_version }}
          name: "Release ${{ env.new_version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.QQQ }}
