name: Auto Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_version
        run: |
          latest_tag=$(git ls-remote --tags --sort="v:refname" origin | tail -n1 | awk -F'/' '{print $NF}')
          if [[ -z "$latest_tag" ]]; then
            latest_tag="v1.0.0"
          else
            latest_version=$(echo $latest_tag | sed 's/v//')
            IFS='.' read -r major minor patch <<< "$latest_version"
            patch=$((patch + 1))
            latest_tag="v$major.$minor.$patch"
          fi
          echo "new_version=$latest_tag" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_version }}
          draft: false
          prerelease: false
          files: '**/*.py' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
